version: '3'
services:
  ovs_container1:
    container_name: ubun_cont_ovs1
    image: bibinvninan/ovs:ovs_installed_ubuntu
    #command: tail -f /dev/null
    command: ["sleep","infinity"]
    cap_add:
      - NET_ADMIN
    network_mode: none

  ovs_container2:
    container_name: ubun_cont_ovs2
    image: bibinvninan/ovs:ovs_installed_ubuntu
    #command: tail -f /dev/null
    command: ["sleep","infinity"]
    cap_add:
      - NET_ADMIN
    network_mode: none
  
  ubuntu_container1:
    container_name: ubuntu_red
    image: bibinvninan/ubuntu_updated:no_interface
    #command: tail -f /dev/null
    command: ["sleep","infinity"]
    cap_add:
      - NET_ADMIN
    network_mode: none

  ubuntu_container2:
    container_name: ubuntu_blue
    image: bibinvninan/ubuntu_updated:no_interface
    #command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    command: ["sleep","infinity"]
    network_mode: none
